inherit_from: .rubocop_todo.yml

# Broken on 1.9
Style/HashSyntax:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false