version: '3'
services:
  sns:
    image: s12v/sns
    ports:
      - "9911:9911"
  s3:
    image: minio/minio:latest
    command: ["server", "/data"]
    ports:
      - "9000:9000"
  dynamodb:
    image: circleci/dynamodb
    ports:
      - "8000:8000"
  sqs:
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"
      - "9325:9325"
